---
title: Single Page Template
description: site description
meta_img: https://uploads.democrats.org/Dev_assets/facebook_D_logo.png
twitter:
favicon:  
url:
ga:
gtm:
timezone: America/New York
future: true
livereload: true
markdown: kramdown
kramdown:
  auto_ids: false
theme: minima
gems:
- jekyll-feed
- jekyll-admin
- uglifier
exclude:
- Gemfile
- Gemfile.lock
- node_modules
sass:
  sass_dir: _sass
  style: compressed
defaults:
- scope:
    path: ''
  values:
    layout: index
# collections:
#   collection-name:
#     output: true
